/*
 * Quality — the sidecar for judgments, and the reader for the reports a
 * detector run drops on disk.
 *
 * THE SENTENCE THAT GOVERNS THE WHOLE DESIGN: the sidecar stores judgments
 * only; observations live in the run and are disposable. `reports/` is
 * regenerated by whatever produced it — a CI job, a hand run, later a
 * `quality-runner.js` — and this module treats it as READ ONLY input, never
 * rewriting or pruning it. `judgments.json` and `state.json` are the only
 * things this module writes, because they are the only things a person's
 * triage session actually needs to survive the NEXT run overwriting
 * `reports/` wholesale. Losing a report costs nothing but a re-run; losing a
 * judgment costs a colleague's afternoon of reading.
 *
 * THE LAYOUT, exactly as CONTRACT-quality.md §5 and §6 specify it:
 *
 *   <root>/.studio/quality/reports/          detector output, as dropped in
 *      bloat/<name>.json                     one document's duplication report
 *      purpose/<name>.json                   one document's purpose report
 *      bloat-docset/<docset>.json            cross-document duplication
 *      trace-<docset>.json                   link verdicts
 *   <root>/.studio/quality/judgments.json    fingerprint -> judgment. WRITTEN.
 *   <root>/.studio/quality/state.json        doc-type overrides + last-run fingerprints
 *
 * `reports/` — `runId` fixed at `'reports'` — was the only thing this module
 * read while `quality-runner.js` did not exist yet: the one hand-dropped
 * directory PLAN-quality.md §11 describes for phase 1. It still is exactly
 * that: read-only, never pruned, `runId: 'reports'` unchanged.
 *
 * `runs/<runId>/` (CONTRACT-runner.md §2) is the SECOND reader promised above,
 * added rather than rewritten: `listRuns`, `loadManifest`, and an optional
 * `{ runId }` on `loadReports` that defaults to the newest FINISHED run and
 * falls back to `reports/` when no run exists at all. Nothing about how a
 * report file is read, matched, or shaped changed — a run directory holds the
 * exact same `bloat/`, `purpose/`, `bloat-docset/` and `trace-*.json` layout,
 * plus one file this module didn't previously have to ignore: `manifest.json`.
 *
 * WHAT THIS MODULE IS NOT. It does not normalise the four detector shapes into
 * the envelope (§2), it does not band trust, it does not compute a fingerprint,
 * and it does not reconcile a run against a previous one — that is
 * `quality-scan.js`'s job, entirely, and it is a pure module for exactly the
 * reason `search-scan.js` gives at its own head: the hard questions deserve a
 * checkable answer in node, not a browser. This module's only jobs are I/O
 * (read the files, watch the directory) and the one piece of matching logic
 * that has nowhere else to live because it is needed just to figure out WHICH
 * raw report belongs to which open document — see `matchReport` below. So the
 * shape-checking here is deliberately shallow: enough to route a parsed file
 * into the right bucket and to know it is not garbage, not a re-implementation
 * of the detector contract. That validation belongs to whatever reads these
 * arrays next.
 *
 * Same storage decision comments and changes already made: a sidecar inside
 * the repository, not a Studio-side database, committed with the branch and
 * reviewable as an ordinary diff. `changes-store.js` is the shape this file
 * copies — same `rootFor`, same `readJson`/`writeJson`, same `BinaryBuffer`
 * fallback for a file that does not exist yet, same longest-matching-root rule.
 */

const { URI } = require('@theia/core/lib/common/uri');
const { identity, authorRecord } = require('./identity');

const QUALITY_DIR = '.studio/quality';
const REPORTS_SUBDIR = 'reports';
const RUNS_SUBDIR = 'runs';
const MANIFEST_FILE = 'manifest.json';
const JUDGMENTS_FILE = 'judgments.json';
const STATE_FILE = 'state.json';

const BLOAT_SUBDIR = 'bloat';
const PURPOSE_SUBDIR = 'purpose';
const DOCSET_SUBDIR = 'bloat-docset';
const TRACE_PREFIX = 'trace-';
const TRACE_SUFFIX = '.json';

/* A report set this size arrives as dozens of files written together (one CI
 * job, one hand-copy). Firing on the first file and re-reading on every one of
 * the rest would repaint the rail dozens of times for one event a person
 * experiences as instantaneous. Longer than comment-log's 150ms because a
 * report drop is a bigger burst than one person's keystroke-paced append. */
const WATCH_DEBOUNCE_MS = 300;

/*
 * The reason vocabulary — CONTRACT-quality.md §4, closed on purpose.
 *
 * This is the only ground truth the product can ever generate about whether a
 * detector is any good: "not-a-duplicate" and "wrong-doc-type" are votes
 * against the detector, "deliberate" and "wont-fix" are votes for it. A free
 * text reason would feel more expressive and would produce nothing anyone
 * could ever aggregate into a false-positive rate. So a value outside this set
 * is refused rather than stored — storing it "just this once" is exactly how a
 * closed vocabulary stops being closed.
 */
const REASONS = new Set(['not-a-duplicate', 'deliberate', 'wont-fix', 'wrong-doc-type']);

/*
 * The project-relative path a document is addressed by, everywhere in this
 * feature. Identical to changes-store.js's `relativePath` — re-implemented
 * rather than imported, because CONTRACT-quality.md §1 draws this module's
 * dependency line at `@theia/core/lib/common/uri`, `@theia/core/lib/common/buffer`
 * and `./identity`, and a shared root-relative-path rule split across two
 * modules that both hand-copy it is a smaller risk than a new inter-module
 * dependency between two files that otherwise have nothing to do with each
 * other.
 */
function relativePath(rootUri, docUri) {
    const rootStr = rootUri.toString();
    const docStr = docUri.toString();
    return docStr.startsWith(rootStr) ? docStr.slice(rootStr.length).replace(/^\//, '') : docUri.path.base;
}

/* Non-empty path segments, so a leading/trailing slash or a doubled separator
 * never turns into a phantom empty segment that could "match" another empty
 * segment in an unrelated path. */
function pathSegments(path) {
    return String(path || '').split('/').filter(Boolean);
}

/*
 * The path a report declares about itself — CONTRACT-quality.md §5's
 * `report.path` for purpose, `report.paths[0]` for bloat (both per-document and
 * docset shapes store an array; only the single-document ones are ever passed
 * to matchReport, so index 0 is always the right — and only — entry there).
 * Reading both shapes through one accessor is what lets matchReport itself stay
 * ignorant of which of the two detector outputs it was handed.
 */
function reportPath(report) {
    if (!report) { return undefined; }
    if (typeof report.path === 'string') { return report.path; }
    if (Array.isArray(report.paths) && typeof report.paths[0] === 'string') { return report.paths[0]; }
    return undefined;
}

/* How many trailing segments two path-segment arrays share, walking from the
 * end inward. Two paths that diverge at the very first (i.e. last-indexed)
 * segment score 0 and are not candidates at all. */
function suffixMatchLength(a, b) {
    let n = 0;
    while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n]) { n++; }
    return n;
}

/*
 * Match a report to a document by longest common path suffix — pure, and
 * exported so the test suite can drive it without a fileService.
 *
 * THE FAILURE MODE THIS AVOIDS. The detectors record their own root-relative
 * path — `tests/traceability/assess/mcp-engine/PRD.md` — which has nothing to
 * do with the Studio project root the document actually opened under. If this
 * matched on basename alone, every `PRD.md` in a six-service repository would
 * resolve to whichever report happened to be first (or last) in the array, and
 * the rail would show a reviewer another service's findings with total
 * confidence — worse than showing nothing, because nothing at least asks a
 * question. So a match must share at least one FULL path segment, never a
 * partial string inside one, and the report whose declared path shares the
 * MOST trailing segments with the open document wins.
 *
 * TIES. With only a basename in common, "mcp-engine/PRD.md" and
 * "gears-frontx/PRD.md" are both distance-1 matches for a bare `PRD.md` opened
 * outside either service's folder — which is exactly the ambiguous case above,
 * just caught one level up instead of at zero segments. Guessing between them
 * is the wrong-service failure again, only quieter, so a genuine tie at the
 * best score is treated as NO match rather than an arbitrary pick. That keeps
 * the honest "no report for this document" state (CONTRACT-quality.md §5)
 * available for an ambiguous document instead of collapsing it into a
 * confidently wrong one.
 */
function matchReport(reports, relPath) {
    const target = pathSegments(relPath);
    if (!target.length) { return undefined; }
    let best = 0;
    let winners = [];
    for (const report of (reports || [])) {
        const declared = reportPath(report);
        if (!declared) { continue; }
        const len = suffixMatchLength(pathSegments(declared), target);
        if (len < 1) { continue; }
        if (len > best) { best = len; winners = [report]; }
        else if (len === best) { winners.push(report); }
    }
    return winners.length === 1 ? winners[0] : undefined;
}

class QualityStore {

    constructor(fileService, workspaceService) {
        this.fileService = fileService;
        this.workspaceService = workspaceService;
    }

    /* Longest matching workspace root — exactly changes-store.js's rule, so a
     * document resolves to the same root under both stores and a quality
     * judgment lands next to the same file's pending proposals. */
    async rootFor(uri) {
        const roots = await this.workspaceService.roots;
        const match = roots
            .filter(r => uri.toString().startsWith(r.resource.toString()))
            .sort((a, b) => b.resource.toString().length - a.resource.toString().length)[0];
        return match ? match.resource : uri.parent;
    }

    reportsUri(rootUri) { return new URI(rootUri.toString() + '/' + QUALITY_DIR + '/' + REPORTS_SUBDIR); }
    judgmentsUri(rootUri) { return new URI(rootUri.toString() + '/' + QUALITY_DIR + '/' + JUDGMENTS_FILE); }
    stateUri(rootUri) { return new URI(rootUri.toString() + '/' + QUALITY_DIR + '/' + STATE_FILE); }
    runsUri(rootUri) { return new URI(rootUri.toString() + '/' + QUALITY_DIR + '/' + RUNS_SUBDIR); }
    runUri(rootUri, runId) { return new URI(this.runsUri(rootUri).toString() + '/' + runId); }
    manifestUri(rootUri, runId) { return new URI(this.runUri(rootUri, runId).toString() + '/' + MANIFEST_FILE); }

    async readJson(uri, fallback) {
        try {
            if (!(await this.fileService.exists(uri))) { return fallback; }
            return JSON.parse((await this.fileService.read(uri)).value);
        } catch (e) {
            console.warn('[studio] could not read', uri.toString(), e);
            return fallback;
        }
    }

    /* Same shape as changes-store.js's writeJson: `fileService.write` fails
     * outright on a file that does not exist yet (there is nothing to
     * overwrite), so the fallback path creates it instead of treating that as
     * a real error. */
    async writeJson(uri, value) {
        const body = JSON.stringify(value, undefined, 2) + '\n';
        try {
            await this.fileService.write(uri, body);
        } catch (e) {
            const { BinaryBuffer } = require('@theia/core/lib/common/buffer');
            await this.fileService.createFile(uri, BinaryBuffer.fromString(body), { overwrite: true });
        }
        return uri;
    }

    /* One JSON report file, parsed defensively. A single malformed or
     * half-written file must cost this one file, never the whole rail — the
     * same reasoning comment-log.js gives for skipping one malformed op line
     * instead of failing the whole fold. */
    async readJsonReport(uri) {
        try {
            return JSON.parse((await this.fileService.read(uri)).value);
        } catch (e) {
            console.warn('[studio] could not read a quality report', uri.toString(), e);
            return undefined;
        }
    }

    /*
     * Every file directly under one report subdirectory (bloat/, purpose/ or
     * bloat-docset/), each checked against `isValidShape` before being kept.
     *
     * `read` and `skipped` on the shared `result` are the reason this exists as
     * a loop rather than a one-liner map/filter: this product's rule, stated
     * plainly in search-scan.js's own header, is that "nothing found" and "we
     * stopped reading" must never look alike. A directory with one unreadable
     * file and three good ones must report 3 read / 1 skipped, not silently 3
     * findings as if that were the whole story.
     */
    async readReportFiles(dirUri, into, isValidShape, result, noteMtime) {
        let stat;
        try {
            stat = await this.fileService.resolve(dirUri, { resolveMetadata: true });
        } catch (e) {
            // The subdirectory named in the top-level listing vanished, or is
            // unreadable, between the listing and this call. Counted as
            // skipped rather than thrown, for the same reason search-view.js's
            // walk() gives for a directory that disappears mid-walk.
            console.warn('[studio] could not list', dirUri.toString(), e);
            result.skipped++;
            return;
        }
        for (const child of (stat && stat.children) || []) {
            if (child.isDirectory || !child.resource.path.base.endsWith('.json')) {
                result.skipped++;
                continue;
            }
            noteMtime(child.mtime);
            const parsed = await this.readJsonReport(child.resource);
            if (parsed && isValidShape(parsed)) {
                into.push(parsed);
                result.read++;
            } else {
                // Parsed as JSON but not shaped like a report this build
                // recognises, or failed to parse at all (readJsonReport already
                // warned in that case). Either way: skipped, not silently
                // absorbed into "nothing to show".
                result.skipped++;
            }
        }
    }

    /*
     * `manifest.json` for one run, parsed defensively — same discipline as
     * `readJsonReport`, and reusing `readJson`'s existing fallback-on-parse-
     * failure rather than a third copy of that try/catch.
     *
     * Returns `undefined` for a run with no manifest at all AND for one whose
     * manifest exists but will not parse or is not a JSON object: from this
     * store's point of view those two are the same fact — "nothing usable to
     * say about this run" — and CONTRACT-runner.md §2 makes manifest.json
     * optional cargo, never the reason a run's reports go unread (see
     * `loadReports` below).
     */
    async loadManifest(rootUri, runId) {
        const data = await this.readJson(this.manifestUri(rootUri, runId), undefined);
        return (data && typeof data === 'object' && !Array.isArray(data)) ? data : undefined;
    }

    /*
     * Every run directory under `.studio/quality/runs/`, newest first, with
     * its manifest already loaded (or `undefined` — see `loadManifest`).
     *
     * SORTED BY STRING, NOT BY DATE. `<runId>` is `YYYYMMDD-HHMMSS` in UTC
     * (CONTRACT-runner.md §2) — a fixed-width, zero-padded, big-endian-ish
     * timestamp — so lexicographic order on the id IS chronological order.
     * Parsing each id into a `Date` to compare them would be a slower, more
     * failure-prone way to compute the same answer, for a format designed
     * specifically so that string comparison already gives it.
     *
     * An empty array means "no runs/ directory, or an empty one" — both read
     * as "no run has ever executed here", which `loadReports` turns into the
     * `reports/` fallback rather than an error.
     */
    async listRuns(rootUri) {
        const dirUri = this.runsUri(rootUri);
        if (!(await this.fileService.exists(dirUri))) { return []; }

        let top;
        try {
            top = await this.fileService.resolve(dirUri, { resolveMetadata: true });
        } catch (e) {
            console.warn('[studio] could not list the quality runs', dirUri.toString(), e);
            return [];
        }

        const runs = [];
        for (const child of (top && top.children) || []) {
            if (!child.isDirectory) { continue; } // a stray file directly under runs/ is not a run
            const runId = child.resource.path.base;
            runs.push({ runId, dir: child.resource, manifest: await this.loadManifest(rootUri, runId) });
        }
        runs.sort((a, b) => (a.runId < b.runId ? 1 : a.runId > b.runId ? -1 : 0));
        return runs;
    }

    /*
     * A run's manifest says it is still being written when it parses but
     * carries no `finishedAt` (CONTRACT-runner.md §4 writes that key only at
     * the end of a run). A run with NO manifest, or one that will not parse,
     * carries no such evidence either way — `loadManifest` already folds both
     * into `undefined` — so it is NOT treated as half-written: the reports
     * inside it are exactly as readable as any other run's, and refusing to
     * pick it as "newest" on the strength of a missing or corrupt sidecar file
     * would be guessing, not caution.
     */
    isHalfWrittenRun(run) {
        return !!(run && run.manifest && !run.manifest.finishedAt);
    }

    /*
     * The shared walk over one report-bearing directory — `reports/` or one
     * run under `runs/<runId>/` — factored out of `loadReports` because the
     * two are, deliberately, the SAME layout: `bloat/`, `purpose/`,
     * `bloat-docset/` and `trace-<docset>.json` (CONTRACT-runner.md §2 vs
     * CONTRACT-quality.md §5). `meta.ignoreTopLevelFiles` is the one place
     * they differ — a run directory also holds `manifest.json`, which is
     * neither a report nor garbage, so it must count toward neither `skipped`
     * nor `producedAt`'s mtime scan; it already has its own, more truthful
     * timestamp in `finishedAt`, folded in by the caller below.
     */
    async readReportSet(dirUri, meta) {
        const result = {
            present: false,
            runId: meta.runId,
            source: meta.source,
            producedAt: undefined,
            bloat: [], purpose: [], docsets: [], traces: [],
            read: 0, skipped: 0
        };
        if (meta.manifest) { result.manifest = meta.manifest; }

        if (!(await this.fileService.exists(dirUri))) { return result; }

        let top;
        try {
            /*
             * `resolveMetadata: true` IS REQUIRED, not defensive. Theia's
             * FileService returns children without an `mtime` unless metadata is
             * asked for, and `producedAt` is the newest mtime under this
             * directory — so without it every run reported "never checked", in a
             * panel whose whole claim is that it always says how old it is. The
             * failure was invisible in a node-fs test stub, which supplies mtime
             * on every stat, and visible only in the running application.
             */
            top = await this.fileService.resolve(dirUri, { resolveMetadata: true });
        } catch (e) {
            console.warn('[studio] could not list the quality reports', dirUri.toString(), e);
            return result;
        }

        /* producedAt falls back to the newest mtime seen anywhere under this
         * directory, because reports dropped by hand or by CI carry no
         * timestamp of their own (CONTRACT-quality.md §5). A run supplies a
         * more truthful one via manifest.finishedAt, folded in below; this scan
         * still runs so the fallback is ready for a run whose manifest is
         * missing or half-written. Tracked as files are read rather than by a
         * second walk, so an unreadable file still contributes the mtime the
         * directory listing already gave us for free. */
        let newestMtime = 0;
        const noteMtime = m => { const v = Number(m) || 0; if (v > newestMtime) { newestMtime = v; } };
        const ignoreTopLevelFiles = new Set(meta.ignoreTopLevelFiles || []);

        for (const child of (top && top.children) || []) {
            const name = child.resource.path.base;
            if (child.isDirectory) {
                if (name === BLOAT_SUBDIR) {
                    await this.readReportFiles(child.resource, result.bloat,
                        r => Array.isArray(r.paths) && typeof r.paths[0] === 'string', result, noteMtime);
                } else if (name === PURPOSE_SUBDIR) {
                    await this.readReportFiles(child.resource, result.purpose,
                        r => typeof r.path === 'string', result, noteMtime);
                } else if (name === DOCSET_SUBDIR) {
                    await this.readReportFiles(child.resource, result.docsets,
                        r => Array.isArray(r.paths) && r.paths.length > 0, result, noteMtime);
                } else {
                    // A directory this build does not recognise — a future
                    // report kind, or debris. Left unread rather than thrown
                    // on: one unknown folder must not blank every kind this
                    // build DOES understand.
                    result.skipped++;
                }
                continue;
            }
            if (ignoreTopLevelFiles.has(name)) {
                // manifest.json under a run directory: already read via
                // loadManifest, and expected to be there — not part of the
                // report set, and not garbage either, so it must inflate
                // neither `skipped` nor the mtime fallback it is meant to be
                // an improvement over.
                continue;
            }
            // Top-level files: only `trace-<docset>.json` is recognised.
            noteMtime(child.mtime);
            if (name.startsWith(TRACE_PREFIX) && name.endsWith(TRACE_SUFFIX)) {
                const parsed = await this.readJsonReport(child.resource);
                if (parsed && Array.isArray(parsed.verdicts)) {
                    result.traces.push(parsed);
                    result.read++;
                } else {
                    result.skipped++;
                }
            } else {
                result.skipped++;
            }
        }

        result.present = true;
        result.producedAt = (meta.manifest && meta.manifest.finishedAt)
            ? meta.manifest.finishedAt
            : (newestMtime ? new Date(newestMtime).toISOString() : undefined);
        return result;
    }

    /*
     * The raw report set for one project root, read fresh every call.
     *
     * `present: false` — an absent directory — is a real, designed state:
     * "analysis has not run here yet", never an empty panel dressed up as a
     * clean document and never a thrown exception a caller has to guard
     * against. `present: true` means the directory exists, whether or not it
     * currently holds anything this build can read; the `read`/`skipped`
     * counters are what say how much of it actually came through.
     *
     * `options.runId` picks WHICH directory:
     *
     *   - `'reports'` (the `REPORTS_SUBDIR` constant) reads the hand-drop
     *     directory explicitly, exactly as this method always has.
     *   - any other id reads that one run under `runs/<runId>/` — useful for
     *     "show me what an older run said", not just the latest.
     *   - omitted (the default, and every existing call site) reads the
     *     newest FINISHED run (`isHalfWrittenRun` says what disqualifies one),
     *     and falls back to `reports/` when no run exists at all, or every run
     *     that exists is still being written. This is the fallback
     *     CONTRACT-runner.md §2 promises: a hand-dropped report set must keep
     *     rendering exactly as it does today on a root `quality-runner.js` has
     *     never touched.
     *
     * Every field this method has always returned keeps its exact meaning;
     * `source` ('run' | 'reports') and `manifest` (present only when a run
     * supplied one that parsed) are additions, not replacements — every caller
     * written against the old shape keeps working unchanged.
     */
    async loadReports(rootUri, options) {
        const requestedRunId = options && options.runId;

        if (requestedRunId === REPORTS_SUBDIR) {
            return this.readReportSet(this.reportsUri(rootUri), { runId: REPORTS_SUBDIR, source: 'reports' });
        }

        if (requestedRunId) {
            const manifest = await this.loadManifest(rootUri, requestedRunId);
            return this.readReportSet(this.runUri(rootUri, requestedRunId), {
                runId: requestedRunId, source: 'run', manifest, ignoreTopLevelFiles: [MANIFEST_FILE]
            });
        }

        const runs = await this.listRuns(rootUri);
        const newestFinished = runs.find(run => !this.isHalfWrittenRun(run));
        if (newestFinished) {
            return this.readReportSet(newestFinished.dir, {
                runId: newestFinished.runId, source: 'run', manifest: newestFinished.manifest,
                ignoreTopLevelFiles: [MANIFEST_FILE]
            });
        }

        return this.readReportSet(this.reportsUri(rootUri), { runId: REPORTS_SUBDIR, source: 'reports' });
    }

    /*
     * Which bloat and purpose report — if any — belong to one open document.
     * A thin wrapper over `matchReport`, kept as a method (rather than folding
     * its two calls into every call site) because a caller should never have
     * to know that bloat and purpose live in two separate arrays inside
     * `reports`; that is this store's layout to own, not the rail's.
     */
    reportsForDocument(reports, relPath) {
        return {
            bloat: matchReport(reports && reports.bloat, relPath),
            purpose: matchReport(reports && reports.purpose, relPath)
        };
    }

    /* `{}` when the sidecar does not exist yet — a project with no judgments
     * ever recorded is the common case, not an error. A file that fails to
     * parse falls back to `{}` too (readJson already warned); this store
     * would rather show every finding as un-triaged than throw on a project
     * whose sidecar somebody hand-edited badly. */
    async loadJudgments(rootUri) {
        const data = await this.readJson(this.judgmentsUri(rootUri), undefined);
        return (data && typeof data === 'object' && !Array.isArray(data)) ? data : {};
    }

    /*
     * Merge-write one judgment. Read the whole map, set exactly the one key
     * this call is about, write the whole map back.
     *
     * THIS IS A READ-MODIFY-WRITE, and it is not safe against two people
     * triaging the same project between one one's read and the other's write —
     * that race is real, and this store does not try to be clever about it.
     * `judgments.json` is a COMMITTED file (CONTRACT-quality.md §4), so the
     * honest resolution of two colleagues' concurrent judgments landing on the
     * same clone at the same moment is a git merge conflict on that line, the
     * same way it would be for any other text file two people edited at once —
     * not a CRDT, not a lock, not an appended log the way comment-log.js uses
     * to make concurrent authorship structurally safe. Comments needed that
     * because two people are expected to comment on the same document at the
     * same time as a matter of course; two people dismissing the SAME
     * duplicate finding at the SAME instant is rare enough that a merge
     * conflict — which git already shows a person how to resolve — is a
     * proportionate answer, and building the append-only machinery twice for a
     * much rarer race is not.
     *
     * Every write here is a real judgment about somebody's repository, so it
     * is attributed: `actor` from identity.js's author record, `at` an ISO
     * timestamp stamped fresh on every write regardless of what the caller
     * passed in — an override here would let a stale client claim a
     * judgment happened earlier than it did.
     */
    async saveJudgment(rootUri, fingerprint, record) {
        if (!fingerprint) { throw new Error('[studio] a judgment needs a fingerprint to key it by'); }
        const status = (record && record.status) || 'dismissed';
        const reason = record && record.reason;

        /* The reason vocabulary is closed (see REASONS above). A dismissal
         * without one of the four keys is refused outright rather than stored
         * with an empty or made-up reason, because a silently-accepted
         * placeholder here is indistinguishable later from a real answer and
         * would poison the one signal this feature can ever produce about
         * whether a detector is worth trusting. `later` carries no reason in
         * the UI (PLAN-quality.md §6) and is not required to supply one. */
        if (status === 'dismissed' && !REASONS.has(reason)) {
            throw new Error('[studio] a dismissed judgment needs a reason, one of: ' + [...REASONS].join(', '));
        }
        if (reason !== undefined && !REASONS.has(reason)) {
            throw new Error('[studio] unknown judgment reason: ' + reason);
        }

        const uri = this.judgmentsUri(rootUri);
        const judgments = await this.loadJudgments(rootUri);
        judgments[fingerprint] = {
            status,
            reason: reason || undefined,
            note: (record && record.note) || '',
            actor: authorRecord(identity.current()),
            at: new Date().toISOString()
        };
        await this.writeJson(uri, judgments);
        return judgments[fingerprint];
    }

    /*
     * The undo path. Deletes the one key rather than writing a tombstone,
     * because a cleared judgment is not a fact worth remembering the way a
     * retracted comment is (comment-log.js keeps tombstones because a log
     * cannot forget by construction) — this sidecar is a plain map, so
     * "forget this fingerprint" is just "the key is gone", and the finding
     * goes back to being un-triaged on the next fold rather than triaged as
     * "cleared".
     */
    async clearJudgment(rootUri, fingerprint) {
        const uri = this.judgmentsUri(rootUri);
        const judgments = await this.loadJudgments(rootUri);
        if (!(fingerprint in judgments)) { return; }
        delete judgments[fingerprint];
        await this.writeJson(uri, judgments);
    }

    /*
     * `overrides` — the document-type correction PLAN-quality.md §5 calls "the
     * highest-leverage control in the whole feature", keyed by relative path.
     * `lastRun` — the fingerprints reconcile() diffs the NEXT run against, also
     * keyed by relative path, so "3 findings resolved since the last check"
     * can be computed without keeping every past run's envelope around.
     */
    async loadState(rootUri) {
        const data = await this.readJson(this.stateUri(rootUri), undefined);
        const overrides = data && data.overrides && typeof data.overrides === 'object' && !Array.isArray(data.overrides)
            ? data.overrides : {};
        const lastRun = data && data.lastRun && typeof data.lastRun === 'object' && !Array.isArray(data.lastRun)
            ? data.lastRun : {};
        return { overrides, lastRun };
    }

    /* Same merge-write discipline as saveJudgment: read the whole state file,
     * set one document's override, write it back. */
    async saveDocTypeOverride(rootUri, relPath, docType) {
        const uri = this.stateUri(rootUri);
        const state = await this.loadState(rootUri);
        state.overrides[relPath] = { docType };
        await this.writeJson(uri, state);
        return state.overrides[relPath];
    }

    /* Recorded on every successful check, so the run after this one can tell
     * "still here" from "resolved" from "new" (PLAN-quality.md §12) without
     * this store having to know anything about reconciliation itself — it only
     * has to remember what the fingerprints were last time. */
    async saveLastRun(rootUri, relPath, fingerprints) {
        const uri = this.stateUri(rootUri);
        const state = await this.loadState(rootUri);
        state.lastRun[relPath] = Array.isArray(fingerprints) ? fingerprints.slice() : [];
        await this.writeJson(uri, state);
        return state.lastRun[relPath];
    }

    /*
     * Notify when anything under `.studio/quality/` changes, so a report
     * dropped in from CI — or a colleague's judgment landing from a pull —
     * appears without polling. Modelled directly on comment-log.js's watch():
     *
     *  - the DIRECTORY is watched, not any one file inside it, because
     *    `onDidFilesChange` only reports resources something has asked to
     *    watch (the trap repositories-view.js and comment-log.js both
     *    document), and a report set can appear in a project that has never
     *    had a `.studio/quality/` directory before this moment;
     *  - the callback fires on a plain debounce rather than tracking this
     *    client's own writes, because re-reading is cheap and idempotent and a
     *    suppressed event is the expensive failure — a colleague's or CI's
     *    change silently never appearing — while a redundant re-read costs one
     *    small extra read.
     *
     * Unlike comment-log's watch, this one does not hand the caller a reloaded
     * payload: `.studio/quality/` covers three logically separate things
     * (read-only reports, judgments, doc-type/last-run state), and a single
     * change event says nothing about which of the three moved. Handing back
     * one of them would misrepresent the other two as unchanged. So the
     * callback is a plain signal — "something under here moved, re-load
     * whichever of loadReports/loadJudgments/loadState you actually render" —
     * and the caller decides what that means for its own screen.
     */
    watch(rootUri, onChanged) {
        const dirUri = new URI(rootUri.toString() + '/' + QUALITY_DIR);
        const prefix = dirUri.toString() + '/';
        const disposables = [];
        try {
            disposables.push(this.fileService.watch(dirUri));
        } catch (e) {
            console.warn('[studio] could not watch the quality sidecar', dirUri.toString(), e);
        }
        let timer;
        disposables.push(this.fileService.onDidFilesChange(event => {
            const touched = (event && event.changes ? event.changes : [])
                .some(change => change.resource && change.resource.toString().startsWith(prefix));
            if (!touched) { return; }
            clearTimeout(timer);
            timer = setTimeout(() => {
                try { onChanged(); } catch (e) { console.error('[studio] quality watch callback failed', e); }
            }, WATCH_DEBOUNCE_MS);
        }));
        return {
            dispose() {
                clearTimeout(timer);
                disposables.forEach(d => { try { d && d.dispose && d.dispose(); } catch (e) { /* already disposed */ } });
                disposables.length = 0;
            }
        };
    }
}

module.exports = { QualityStore, QUALITY_DIR, matchReport, relativePath };
