/**
 * Header Component
 *
 * Application header with user info display.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import { useAppSelector, useAppDispatch, clearUser, type HeaderState } from '@gears-frontx/react';
import { Avatar, AvatarImage, AvatarFallback } from '@/app/components/ui/avatar';
import { Skeleton } from '@/app/components/ui/skeleton';
import { keycloakOidcProvider } from '@/app/auth/keycloakOidcProvider';

export interface HeaderProps {
  children?: React.ReactNode;
}

export const Header: React.FC<HeaderProps> = ({ children }) => {
  const headerState = useAppSelector((state) => state['layout/header'] as HeaderState | undefined);
  const dispatch = useAppDispatch();

  const user = headerState?.user;
  const loading = headerState?.loading ?? false;

  const signOut = async () => {
    dispatch(clearUser());
    // RP-initiated logout redirects to the IdP; static-token sessions end
    // locally and the AuthGate flips to the login screen via subscribe().
    const transition = await keycloakOidcProvider.logout();
    if (transition.type === 'redirect') window.location.href = transition.redirectUrl;
  };

  const getInitials = (): string => {
    if (!user?.displayName) return (user?.email?.[0] || '?').toUpperCase();
    const parts = user.displayName.trim().split(/\s+/);
    if (parts.length >= 2) {
      return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase();
    }
    return user.displayName.slice(0, 2).toUpperCase();
  };

  return (
    <header className="h-16 flex items-center px-4 border-b border-border bg-background">
      {children}
      <div className="ml-auto">
        {loading ? (
          <div className="flex items-center gap-2 text-sm">
            <Skeleton className="h-8 w-8 rounded-full" />
            <Skeleton className="h-4 w-24" />
          </div>
        ) : (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Avatar className="h-8 w-8">
              {user?.avatarUrl && <AvatarImage src={user.avatarUrl} alt={user?.displayName || user?.email || 'User'} />}
              <AvatarFallback>{getInitials()}</AvatarFallback>
            </Avatar>
            <span>{user?.displayName || user?.email || 'User'}</span>
            <button
              type="button"
              onClick={() => void signOut()}
              className="ml-2 rounded-md border border-border px-2 py-1 text-xs hover:bg-muted"
            >
              Sign out
            </button>
          </div>
        )}
      </div>
    </header>
  );
};

Header.displayName = 'Header';
