-- Intentionally no CREATE DATABASE statements here.
--
-- docker-entrypoint-initdb.d runs only once for a new volume, which made this
-- list stale whenever a stateful gear was introduced later. `backend-bootstrap`
-- instead discovers `gears.*.database` from config/docker.yaml on every
-- compose start, creates only missing databases, and runs forward migrations.
-- It never drops databases or data.
