/**
 * FrontX Application Component
 *
 * Renders the Layout with MFE screen container.
 * Layout components are generated by `frontx scaffold layout` and owned by the project.
 *
 * FrontXProvider (in main.tsx) handles:
 * - Redux Provider setup
 * - FrontX context (app instance)
 *
 * Layout handles:
 * - Header, Menu, Screen and the overlay frames rendering
 * - Theme-aware styling via hooks
 *
 * MfeScreenContainer handles:
 * - MFE domain registration
 * - MFE extension loading and mounting
 * - DOM container for MFE content
 *
 * StudioOverlay (dev mode only):
 * - Development tools for theme/screenset switching
 * - Language selection
 * - API mode toggle (services register their own mocks)
 */

import { Layout } from '@/app/layout';
import { StudioOverlay } from '@gears-frontx/studio';
import { MfeScreenContainer } from '@/app/mfe/MfeScreenContainer';
import { AuthGate } from '@/app/auth/AuthGate';

function App() {
  return (
    <>
      {/* The authenticated app mounts only behind the gate; the dev overlay
          stays outside so theme/mock toggles work on the login screen too. */}
      <AuthGate>
        <Layout>
          <MfeScreenContainer />
        </Layout>
      </AuthGate>
      <StudioOverlay />
    </>
  );
}

export default App;
